[package]
name = "adventofcode2015"
version = "0.1.0"
authors = ["Adam Perry <adam.n.perry@gmail.com>"]

[dependencies]
clap = "1.5.3"
permutohedron = "0.1.7"
rust-crypto = "0.2.34"
serde_json = "0.6.0"